before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - main: ./cmd
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/cuisongliu/endpoints-balance/library/version.GitVersion={{.Version}}
      - -X github.com/cuisongliu/endpoints-balance/library/version.GitCommit={{.ShortCommit}}
      - -X github.com/cuisongliu/endpoints-balance/library/version.BuildDate={{.Date}}

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
