
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "endpoints-operator.fullname" . }}
  labels:
    {{- include "endpoints-operator.labels" . | nindent 4 }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "endpoints-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  # annotations:
  #   rbac.authorization.kubernetes.io/autoupdate: "true"
roleRef:
  kind: ClusterRole
  name: {{ include "endpoints-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "endpoints-operator.fullname" . }}
    namespace: {{ .Release.Namespace }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{.Release.Namespace}}
  name: {{ include "endpoints-operator.fullname" . }}
rules:
  - apiGroups:
      - '*'
    resources:
      - endpoints
      - services
      - configmaps
      - events
    verbs:
      - '*'
  - apiGroups: 
      - 'sealyun.com'
    resources:
      - clusterendpoints
      - clusterendpoints/status
    verbs:
      - '*'